#pragma once

/*
 * IWaveGenerator interface.
 */
class IWaveGenerator
{
public:
	static const float DefaultLevel;

	// Copies data generated by generate() method to the buffer.
	// Pass value returned by getSampleBufferSize() method as destSize parameter.
	virtual HRESULT copyTo(BYTE* destBuffer, size_t destSize) = 0;
	virtual void generate(float key, float level = DefaultLevel) = 0;

	virtual WORD getFormatTag() const = 0;
	virtual size_t getBlockAlign() const = 0;
	virtual size_t getBitsPerSample() const = 0;
	virtual WORD getSamplesPerSec() const = 0;
	virtual WORD getChannels() const = 0;
	virtual size_t getSampleBufferSize(size_t duration) const = 0;
};

/*
 * WaveGenerator template abstract class
 * Type parameter T is data type of wave sample data.
 *   Such as T=UINT16 for 16 bit per sample per channel.
 *   This case, minimum atomic unit of 2-channel sample is 16 / 8 * 2 byte.
 * 
 * IWaveGenerator::generate() and getFormatTag() methods should be implemented by derived class.
 */
template<typename T>
class WaveGenerator : public IWaveGenerator
{
public:
	WaveGenerator(WORD samplesPerSec, WORD channels)
		: m_samplesPerSec(samplesPerSec), m_channels(channels), m_cycleSize(0), m_currentPosition(0) {}
	virtual ~WaveGenerator() {}

	virtual HRESULT copyTo(BYTE* destBuffer, size_t destSize) override;

	// Returns byte size of the minimum atomic unit of data to be generated.
	virtual size_t getBlockAlign() const override { return m_channels * sizeof(T); }
	virtual size_t getBitsPerSample() const override { return sizeof(T) * 8; }
	virtual WORD getSamplesPerSec() const override { return m_samplesPerSec; }
	virtual WORD getChannels() const override { return m_channels; }
	virtual size_t getSampleBufferSize(size_t duration) const { return m_samplesPerSec * getBlockAlign() * duration / 1000; }

	operator bool() const { return (bool)m_cycleData; }

protected:
	// Allocate buffer enough to hold 1-cycle PCM data.
	void allocateCycleData(float key);

	static const T HighValue;
	static const T LowValue;

	const WORD m_samplesPerSec;
	const WORD m_channels;
	size_t m_cycleSize;
	size_t m_currentPosition;
	std::unique_ptr<T[]> m_cycleData;
};

template<typename T>
HRESULT WaveGenerator<T>::copyTo(BYTE* destBuffer, size_t destSize)
{
	// Assert that data has been generated.
	HR_ASSERT(m_cycleData, E_ILLEGAL_METHOD_CALL);

	for(DWORD destPosition = 0; destPosition < destSize; destPosition += sizeof(T)) {
		*(T*)(&destBuffer[destPosition]) = m_cycleData[m_currentPosition++];
		if(m_cycleSize < m_currentPosition) { m_currentPosition = 0; }
	}

	return S_OK;
}

template<typename T>
void WaveGenerator<T>::allocateCycleData(float key)
{
	m_currentPosition = 0;
	m_cycleSize = (size_t)(m_channels * m_samplesPerSec / key);
	auto blockAlign = getBlockAlign();
	m_cycleSize = (m_cycleSize / blockAlign) * blockAlign;		// Adjust buffer size to block align boundary
	m_cycleData.reset(new T[m_cycleSize]);
}

/*
 * SquareWaveGenerator class derived from WaveGenerator class.
 * 
 * Override of WaveGenerator::generate() method generates Square wave.
 * This class exposes generate() method that has duty parameter along with above.
 */
template<typename T>
class SquareWaveGenerator : public WaveGenerator<T>
{
public:
	static const float DefaultDuty;

	SquareWaveGenerator(WORD samplesPerSec, WORD channels) : WaveGenerator(samplesPerSec, channels) {}

	virtual void generate(float key, float level = DefaultLevel) override;
	void generate(float key, float level, float duty);
};

template<typename T>
void SquareWaveGenerator<T>::generate(float key, float level /*= DefaultLevel*/)
{
	generate(key, level, DefaultDuty);
}

template<typename T>
void SquareWaveGenerator<T>::generate(float key, float level, float duty)
{
	allocateCycleData(key);

	size_t highDuration = (size_t)(m_cycleSize * duty);
	size_t pos = 0;
	for(; pos < highDuration; pos++) {
		for(size_t ch = 0; ch < m_channels; ch++) {
			m_cycleData[pos + ch] = HighValue;
		}
	}
	for(; pos < m_cycleSize; pos++) {
		for(size_t ch = 0; ch < m_channels; ch++) {
			m_cycleData[pos + ch] = LowValue;
		}
	}
}

template<typename T>
/*static*/ const float SquareWaveGenerator<T>::DefaultDuty = 0.5f;

class Square8bpsWaveGenerator : public SquareWaveGenerator<UINT8>
{
public:
	Square8bpsWaveGenerator(WORD samplesPerSec, WORD channels) : SquareWaveGenerator(samplesPerSec, channels) {}

	virtual WORD getFormatTag() const override { return WAVE_FORMAT_PCM; }
};

class Square16bpsWaveGenerator : public SquareWaveGenerator<UINT16>
{
public:
	Square16bpsWaveGenerator(WORD samplesPerSec, WORD channels) : SquareWaveGenerator(samplesPerSec, channels) {}

	virtual WORD getFormatTag() const override { return WAVE_FORMAT_PCM; }
};
